name: Builder
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron:  '0 0 * * *' # Every day at midnight
  workflow_dispatch:
    branches: [ main ]

jobs:

  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
    - name: Create tag
      run: |
        TAG=$(date +%Y%m%d%H%M%S)
        echo $TAG > tag.txt
    - name: Upload tag
      uses: actions/upload-artifact@v3
      with:
        name: tag
        path: tag.txt

  build-debug:
    name: Build debug
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: WITH_DEBUG=true ./build.sh
    - name: Download tag
      uses: actions/download-artifact@v1
      with:
        name: tag
    - name: Package
      run: TAG=`cat tag/tag.txt` WITH_DEBUG=true ./package.sh
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: debug-build
        path: '*.tar.gz'

  build-release:
    name: Build release
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: ./build.sh
    - name: Download tag
      uses: actions/download-artifact@v1
      with:
        name: tag
    - name: Package
      run: TAG=`cat tag/tag.txt` ./package.sh
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: release-build
        path: '*.tar.gz'

  github-release:
    name: Create GitHub release
    needs: [build-debug, build-release]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download builds
      uses: actions/download-artifact@v3
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "debug-build/*.tar.gz,release-build/*.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: nightly
        removeArtifacts: true
        commit: main
        allowUpdates: true