name: Test
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron:  '0 0 * * *' # Every day at midnight
  workflow_dispatch:
    branches: [ main ]

jobs:

  build-test:
    name: Build test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: ./build.sh
    - name: Basic test
      run: cd ruby && make btest
